### ISSUE TITLE
Fix broken hyperlink on https://silentpayments.xyz/docs/wallets/

### ISSUE THREAD

**Issue by GlenCooper** [sethforprivacy/silentpaymentsxyz#13]
I noticed a broken link on your webpage.
I'm not sure how it's all set up, or where to fix the problem in your code, but I thought it was worth mentioning to you since it is reproducible as follows:

Using a Firefox Private browser (129.0.2 64-bit, Mozilla Firefox Snap for Ubuntu, canonical-002 - 1.0),
- Navigate to https://silentpayments.xyz/docs/wallets/
- click on the hyperlink for '[Edit this page on GitHub →](https://github.com/sethforprivacy/silentpaymentsxyz/edit/main/content/docs/wallets.md)' in the upper right, circled here:
![Screenshot from 2024-08-31 12-16-34](https://github.com/user-attachments/assets/42832189-68b7-43cc-8ecf-abc912ab8098)

When you click on that link, you end up at a 404 page:
![Screenshot from 2024-08-31 12-18-02](https://github.com/user-attachments/assets/06b7dac4-14df-4f55-8789-2b1e2b8ac6e6)
  
  
Thank you for all of the stuff you do with bitcoin.

**Comment by GlenCooper** [comment]
P.S. - I zapped you 21 sats to your BOLT12 offer listed on https://sethforprivacy.com/donate/ as lno1zrxq8pjw7qjlm68mtp7e3yvxee4y5xrgjhhyf2fxhlphpckrvevh50u0qgve8erq859ugpp8lzpk2pf8atxrq7s9ljwxvc0lt53yhsdzj592wqszzcmftue8eeeflhks0wkppyug4pl6c5g0uh6pqczez76ekk2t8ewqqvedkpuu3ya8wt0mzeapn0pcjzu6v9aw786fj63htcn03wmghx6pt20ulk3j2wqs2w9245tk8ymt77kezvsqq05t64hk988ah4rgqmf0z4stecyl9acjz865txge7gszqxkka6765qqsyc50jeduhux0qrghey0vsl7ndy
  
Sent from Strike.  It worked.  Cool.  What did you use to craft the BOLT12?

**Comment by sethforprivacy** [comment]
Thanksk for the report, finally figured out what it was and fixed it in https://github.com/sethforprivacy/silentpaymentsxyz/commit/4bc673493c9f298fe6cf4178fab28265d4a88886!

For BOLT 12 I'm using phoenixd, works beautifully.
