### ISSUE TITLE
Silentium not sending to mainchain SP address

### ISSUE THREAD

**Issue by vazertuche** [sethforprivacy/silentpaymentsxyz#9]
I've done4 successful test sending to silent payment address on testnet but I loaded up my mainchain wallet and I can't sent to a mainnet sp1p address. It stays stuck at sending screen.
![IMG_3617](https://github.com/sethforprivacy/silentpaymentsxyz/assets/127354611/61e7e11e-54f8-43b1-9e42-29c540d0d266)

**Comment by sethforprivacy** [comment]
Have you opened an issue in there repo or notified them in some way?

Could be as simple as a back-end server down.

**Comment by sethforprivacy** [comment]
> I didn't see a place to report issues on his github but it was late. You had a nice place to report things on site so I figured I may as well post here. I'll try and post on his repo.

Would be great if you can open an issue on his repo here, similarly to how you did on this repo!

https://github.com/louisinger/silentium

That way y'all can work together to find the fix.
